spring.application.name=ms-universite

server.port=8081
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8888/eureka

# Cache (Caffeine)
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s
spring.cache.cache-names=enseignantCache,formationCache

# Resilience4j CircuitBreaker
resilience4j.circuitbreaker.instances.enseignantCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.enseignantCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.enseignantCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.formationCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.formationCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.formationCB.wait-duration-in-open-state=10s