spring.application.name=ms-universite

server.port=8081
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8888/eureka

# Cache configuration (Caffeine)
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m
spring.cache.cache-names=universiteDetails

# Resilience4j CircuitBreaker configuration
resilience4j.circuitbreaker.instances.enseignantService.sliding-window-size=5
resilience4j.circuitbreaker.instances.enseignantService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.enseignantService.wait-duration-in-open-state=10s